#Evolution of "sensibility" theme in French novels 1751-1800 as relative frenquency
#title:Evolution of sensibility" theme in French novels 1751-1800
#defaultView:BarChart
prefix mmd:<http://data.mimotext.uni-trier.de/entity/> 
prefix mmdt:<http://data.mimotext.uni-trier.de/prop/direct/> 
SELECT ?date (?countSentimental / ?countAll *100 AS ?rel)  ?countSentimental ?countAll 
WHERE {
 {  
   # Subquery to count novels with tonality 'sensibility'
    SELECT ?date (count(*) AS ?countSentimental)
    WHERE {
      ?item mmdt:P9 ?date;
            mmdt:P38 ?topic .
      ?topic rdfs:label ?topicLabel .
      # Filtering for English labels with "travel"
      FILTER(lang(?topicLabel) = "en")
      FILTER(lcase(?topicLabel) = "sensibility"@en)
    }
    GROUP BY ?date
  }
  {
    # Subquery to count all novels
   SELECT ?date (count(*) AS ?countAll)
   WHERE {
     ?item mmdt:P9 ?date;
         mmdt:P36 ?topic . 
     ?topic rdfs:label ?topicLabel .
     filter(lang(?topicLabel) = "en")
   }
   GROUP BY ?date
 }
}