project:
  type: book

book:
  title: "Literaturgeschichte als Wissensgraph"
  subtitle: "Automatische Erhebung literaturhistorisch relevanter Informationen aus Volltexten am Beispiel von französischen Romanen des XVIII. Jahrhunderts"
  author: "Julia Röttgermann"
  date: "2025.04.08"
  search: true
  repo-url: https://github.com/roettger/Thesis
  downloads: [pdf, epub]
  chapters:
  - index.qmd
  - chapter6_stylometry.qmd
  - summary.qmd
  - references.qmd
bibliography: references.bib
csl: DHd.csl
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
    geometry: a4paper
    fontsize: 12pt