project:
  type: book

book:
  title: "Literaturgeschichte als Wissensgraph"
  author: "Julia Röttgermann"
  date: "14.2.2025"
  search: true
  repo-url: https://github.com/roettger/Thesis
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - intro.qmd
    - chapter6_stylometry.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



