# Summary

Die vorliegende Dissertation befasst sich mit der Erstellung eines Wissensgraphen französischer Romane aus der Zeit 1751-1800. Dazu wurde ein Romankorpus erstellt, welches in TEI-konformes XML übertragen und im Rahmen der *European Literary Text Collection* (ELTeC) publiziert wurde. Auf jenes Korpus werden quantitative Methoden der Textanalyse angewendet mit dem Ziel, literaturwissenschaftlich verwertbare Informationen zu Aspekten wie Themen, Orten, Textähnlichkeiten und Sentiments zu extrahieren. Alle extrahierten Daten werden als Linked Open Data in einem Wissensgraphen modelliert, mit weiteren Informationen aus MiMoText verknüpft und mithilfe von strukturierten Abfragen analysiert. Die makrostrukturellen Muster der französischen Literaturgeschichte 1751-1800 werden in SPARQL-Abfragen anaylsiert und im Sinne einer datenbasierten Literaturgeschichtsschreibung interpretiert. 


Keywords: 	*Französischer Roman, Aufklärung, 18. Jahrhundert, Linked Open Data, XML/TEI, Sentiment Analyse, Named Entity Recognition, Topic Modeling, Stilometrie, Wikibase, SPARQL*. In summary, this book has no content whatsoever.
