# imaginary place + Datum 
#defaultView:BarChart
prefix wd:<http://data.mimotext.uni-trier.de/entity/>
prefix wdt:<http://data.mimotext.uni-trier.de/prop/direct/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?date (?countNature / ?countAll AS ?rel)
WHERE {
 {  
   SELECT ?date (count(*) AS ?countNature)
   WHERE {
     ?item wdt:P9 ?date;
           wdt:P36 ?topic .
     ?topic rdfs:label ?topicLabel .
     filter(lang(?topicLabel) = "en")
     filter(lcase(?topicLabel) = "nature"@en)
   }
   GROUP BY ?date
 }
 {
   SELECT ?date (count(*) AS ?countAll)
   WHERE {
     ?item wdt:P9 ?date;
         wdt:P36 ?topic .
     ?topic rdfs:label ?topicLabel .
     filter(lang(?topicLabel) = "en")
   }
   GROUP BY ?date
 }
}
ORDER BY desc(?rel)