#defaultView:BarChart
Select  (str(SAMPLE(year(?date))) as ?year) (count(?themelabel) as ?count) ?themelabel 
   WHERE{
   ?item wdt:P25 ?theme.
   ?theme rdfs:label ?themelabel .
   ?item wdt:P7 ?date .
   FILTER(lang(?themelabel) = "en")
  FILTER(CONTAINS(LCASE(?themelabel), "nature")).
   BIND(str(year(?date)) as ?year)
   SERVICE wikibase:label {bd:serviceParam wikibase:language "{AUTO_LANGUAGE}","en" .}
  }

GROUP BY ?themelabel ?year ?count
#having (?count> 1)